export const styles = {
    dropdown:'text-white text-sm sm:text-base hover:text-gray-300 focus:outline-none mr-7 flex justify-between ',
    dropdownBtn:'text-white px-4 py-1 justify-between flex border-green-500 rounded-md ml-4 border-[1px] hover:bg-gray-700 ',
    btn:'flex item-center justify-center text-gray-800 text-sm sm:text-base border-gray-300 rounded-md py-1 px-2 border-[1.5px] ',
    labelBtn:'py-[1px] px-[5px] text-white text-sm ',
    btnBorderLess:'flex text-black px-2 py-1 rounded-md ml-0 hover:bg-gray-200 ',
    dropdownMenu:'absolute hidden z-50 bg-white p-2 pt-2 text-gray-800 top-8 border-gray-300 border-[1px] ',
    dropdownContainer:'absolute hidden z-50 bg-white p-2 pt-2 w-[180px] overflow-auto max-h-[300px] md:w-[335px] lg:w-[460px] sm:ml-0 text-gray-800 top-8 border-gray-300 border-[1px] ',
    dropdownItem:'text-black p-2 text-sm border-b-[1px] border-gray-100 flex hover:bg-gray-100 ',
    input:'border-[1px] border-gray-300 pl-2 py-2 w-[100%] focus:outline-none focus:border-gray-600 placeholder:text-gray-400 text-sm sm:text-base ',
    title1:'px-2 text-center text-xl sm:text-3xl font-semibold ',
    title2:'text-xl md:text-2xl font-semibold ',
    title3:'text-base md:text-lg lg:text-xl font-semibold ',
    title4:'text-base md:text-lg font-semibold ',
    title2Bold:'text-xl font-bold tracking-wide',
    textMedium:'text-sm sm:text-base ',
    textLarge:'text-base sm:text-lg ',
    paragraph:'text-base text-left py-5 px-4 md:px-11 ',
    // textSmall:'text-sm sm:text-base ',
}